---
language: python
python:
  - 2.7

services:
  - docker

install:
  - docker build -t php-54 .
  - docker run -d -p 127.0.0.1:80:80 --name php-54 php-54

script:
  - wget --quiet 127.0.0.1:80
  - docker ps | grep -q php-54

after_failure:
  - docker logs php-54
...